### ISSUE TITLE
Updates to Pester require changes to Test Scripts

### ISSUE THREAD

**Issue by jberkers42** [ContrarianChris/powershell-module-template#1]
## Expected Behavior

Pester tests included with the template should continue to work on systems running an up-to-date version of Pester.

## Actual Behavior

Pester tests fail with:

```
 RuntimeException: Legacy Should syntax (without dashes) is not supported in Pester 5.  Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
```

Since the requirements in the Build Script already specify Pester version 4.7.3, this should not be a breaking change for anyone using the minimum supported version of Pester for this Template.

## Steps to Reproduce the Problem

  1. Create a new PowerShell Module Skeleton with ```Invoke-Plaster -TemplatePath <Path to Folder> -DestinationPath <Path to Module>```
  1. From within the new module path, run ```Invoke-Build -task Test```

## Specifications

  - Version: Plaster version 1.0
  - Platform: PowerShell Core
  - Subsystem: Pester version 5.2.0

I will submit a pull request with the necessary fixes for this.

**Comment by ekkohnet** [comment]
Thanks for the contribution! Apologies it has taken me so long to get back to this and get it merged.

Closed via #2
